name: Python Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
          pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        coverage run -m unittest discover -s . -v
    - name: Check Code Coverage
      run: |
        sh resources/run_ut.sh
      shell: bash